services:
  rabbitmq:
    image: rabbitmq:management
    container_name: nest_backend_rabbitmq
    restart: always
    env_file:
      - ../.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nest_back_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  nest_back_network:
    name: nest_back_network
    driver: bridge